import { GoogleGenAI } from '@google/genai';
import { GEMINI_MODEL, isGeminiConfigured } from './gemini.util';

export type ReportGeneratorInput = {
  state: string;
  dateFrom: string;
  dateTo: string;
  data: {
    totalCases?: number;
    speciesBreakdown?: Record<string, number>;
    topDiagnoses?: Array<{ name: string; count: number }>;
    locations?: Array<{ name: string; cases: number }>;
    vaccinationsAdministered?: number;
    mortalityCount?: number;
    notes?: string;
  };
};

export type ReportGeneratorResult = {
  state: string;
  dateFrom: string;
  dateTo: string;
  reportMarkdown: string;
  metrics: Record<string, number | string>;
  source: 'ai' | 'fallback';
};

function buildFallbackReport(input: ReportGeneratorInput): ReportGeneratorResult {
  const d = input.data ?? {};
  const total = d.totalCases ?? 0;
  const markdown = `# Disease Surveillance Report — ${input.state}

**Period:** ${input.dateFrom} to ${input.dateTo}

## Summary
- Total cases reported: **${total}**
- Vaccinations administered: **${d.vaccinationsAdministered ?? 0}**
- Mortality count: **${d.mortalityCount ?? 0}**

## Species breakdown
${formatBreakdown(d.speciesBreakdown)}

## Top diagnoses
${formatDiagnoses(d.topDiagnoses)}

## Notes
${d.notes ?? '_No additional notes provided._'}

---
_Generated by Trackpro (template report). Configure GEMINI_API_KEY for AI-enriched narratives._
`;

  return {
    state: input.state,
    dateFrom: input.dateFrom,
    dateTo: input.dateTo,
    reportMarkdown: markdown,
    metrics: {
      totalCases: total,
      vaccinationsAdministered: d.vaccinationsAdministered ?? 0,
      mortalityCount: d.mortalityCount ?? 0,
    },
    source: 'fallback',
  };
}

function formatBreakdown(breakdown?: Record<string, number>): string {
  if (!breakdown || !Object.keys(breakdown).length) return '_No species data._';
  return Object.entries(breakdown)
    .map(([k, v]) => `- ${k}: ${v}`)
    .join('\n');
}

function formatDiagnoses(list?: Array<{ name: string; count: number }>): string {
  if (!list?.length) return '_No diagnosis data._';
  return list.map((x) => `- ${x.name}: ${x.count}`).join('\n');
}

const SYSTEM_PROMPT = `You write official-style Nigerian state livestock disease surveillance reports in Markdown.
Include: executive summary, key metrics, species breakdown, geographic hotspots, recommendations for state veterinary services.
Use the provided data only; do not invent case numbers. Output Markdown only (no JSON wrapper).`;

export async function reportGenerator(input: ReportGeneratorInput): Promise<ReportGeneratorResult> {
  if (!input.state?.trim() || !input.dateFrom?.trim() || !input.dateTo?.trim()) {
    return {
      ...buildFallbackReport({
        ...input,
        state: input.state || 'Unknown',
        dateFrom: input.dateFrom || new Date().toISOString().slice(0, 10),
        dateTo: input.dateTo || new Date().toISOString().slice(0, 10),
      }),
    };
  }

  if (!isGeminiConfigured()) {
    return buildFallbackReport(input);
  }

  try {
    const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY!.trim() });
    const response = await ai.models.generateContent({
      model: GEMINI_MODEL,
      contents: [
        {
          role: 'user',
          parts: [
            {
              text: `${SYSTEM_PROMPT}\n\nState: ${input.state}\nPeriod: ${input.dateFrom} to ${input.dateTo}\n\nData JSON:\n${JSON.stringify(input.data, null, 2)}`,
            },
          ],
        },
      ],
      config: { temperature: 0.3 },
    });

    const reportMarkdown = response.text?.trim();
    if (!reportMarkdown) {
      return buildFallbackReport(input);
    }

    const d = input.data ?? {};
    return {
      state: input.state,
      dateFrom: input.dateFrom,
      dateTo: input.dateTo,
      reportMarkdown,
      metrics: {
        totalCases: d.totalCases ?? 0,
        vaccinationsAdministered: d.vaccinationsAdministered ?? 0,
        mortalityCount: d.mortalityCount ?? 0,
      },
      source: 'ai',
    };
  } catch {
    return buildFallbackReport(input);
  }
}
